name: Deploy to Azure Data Factory

on:
  push:
    branches:
      - main    # Trigger przy pushu do branch `main`

jobs:
  deploy_adf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Azure CLI
      uses: azure/CLI@v1
      with:
        inlineScript: |
          echo "Azure CLI jest gotowe do u≈ºycia"
        
    - name: Enable dynamic extension installation
      run: |
          az config set extension.dynamic_install=yes_without_prompt
    
    - name: Install Azure Data Factory extension
      run: |
          az extension add --name datafactory
    
    - name: Check if adf_pipeline.json exists
      run: |
          echo "Checking adf_pipeline.json:"
          ls -la
          cat ./publish/adf_pipeline.json

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} # Dodaj sekrety w GitHubie

    - name: Deploy to Azure Data Factory
      run: 
        az datafactory pipeline create \
          --resource-group "rg-eh-upskilling-eh-damian.r" \
          --factory-name "adf-damianr1" \
          --name "MainToLivePipeline" \
          --pipeline  @./publish/adf_pipeline.json
